[tool.poetry]
name = "imgencoder"
version = "0.1.0"
description = ""
authors = ["Hengjie Ma <hengjie_ma@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
